/* Generated by re2c 3.1 on Tue Nov 25 20:47:43 2025 */
#line 1 "src/lexer.l"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "common.h"
#include "ast.h"           // 添加 ast.h
#include "parser_types.h"  // 添加 parser_types.h

// 包含 bison 生成的头文件
#include "parser.h"

#define YYCTYPE unsigned char
#define YYCURSOR cursor
#define YYLIMIT limit
#define YYMARKER marker
#define YYFILL(n) {}

// 全局变量用于跟踪输入
ScannerState *global_scanner = NULL;

void set_scanner(ScannerState *scanner) {
    global_scanner = scanner;
}

// 调试函数：打印token信息
void print_token(const char* name, const char* value) {
    printf("LEXER: Token %s", name);
    if (value && strlen(value) > 0) {
        printf(" ('%s')", value);
    }
    printf(" at position %d\n", global_scanner->pos);
}

int yylex(void) {
    const unsigned char *cursor, *marker;
    const unsigned char *start;
    
    if (!global_scanner || !global_scanner->input) {
        printf("LEXER: No input\n");
        return 0;
    }
    
    cursor = (const unsigned char *)global_scanner->input + global_scanner->pos;
    
scan:
    start = cursor;
    

#line 51 "src/lexer.c"
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy1;
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case ' ': goto yy4;
		case '!': goto yy6;
		case '"': goto yy8;
		case '$':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'm':
		case 'o':
		case 'p':
		case 'q':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		case '%': goto yy12;
		case '&': goto yy13;
		case '\'': goto yy14;
		case '(': goto yy15;
		case ')': goto yy16;
		case '*': goto yy17;
		case '+': goto yy19;
		case ',': goto yy21;
		case '-': goto yy22;
		case '.': goto yy24;
		case '/': goto yy26;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy28;
		case ':': goto yy30;
		case ';': goto yy31;
		case '<': goto yy32;
		case '=': goto yy34;
		case '>': goto yy36;
		case '?': goto yy38;
		case '[': goto yy39;
		case ']': goto yy40;
		case '`': goto yy41;
		case 'b': goto yy42;
		case 'c': goto yy43;
		case 'd': goto yy44;
		case 'e': goto yy45;
		case 'f': goto yy46;
		case 'i': goto yy47;
		case 'l': goto yy48;
		case 'n': goto yy49;
		case 'r': goto yy50;
		case 's': goto yy51;
		case 't': goto yy52;
		case 'u': goto yy53;
		case 'v': goto yy54;
		case 'w': goto yy55;
		case '{': goto yy56;
		case '|': goto yy57;
		case '}': goto yy58;
		default: goto yy2;
	}
yy1:
	++YYCURSOR;
#line 376 "src/lexer.l"
	{ 
    printf("LEXER: End of file\n");
    return 0; 
}
#line 162 "src/lexer.c"
yy2:
	++YYCURSOR;
yy3:
#line 382 "src/lexer.l"
	{ 
    fprintf(stderr, "LEXER: Invalid character: %c (0x%02x) at position %d\n", *start, *start, global_scanner->pos);
    global_scanner->pos += cursor - start;
    return 0;  // 返回0表示结束
}
#line 172 "src/lexer.c"
yy4:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case ' ': goto yy4;
		default: goto yy5;
	}
yy5:
#line 52 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    printf("LEXER: Skipped whitespace/newline\n");
    goto scan; 
}
#line 191 "src/lexer.c"
yy6:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy59;
		default: goto yy7;
	}
yy7:
#line 334 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("BANG", ""); return BANG; }
#line 201 "src/lexer.c"
yy8:
	yych = *++YYCURSOR;
	switch (yych) {
		case '"': goto yy61;
		case '\\': goto yy62;
		default: goto yy8;
	}
yy9:
	yych = *++YYCURSOR;
yy10:
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy11;
	}
yy11:
#line 301 "src/lexer.l"
	{
    global_scanner->pos += cursor - start;
    char *text = strndup((char*)start, cursor - start);
    if (!text) {
        fprintf(stderr, "LEXER: Failed to allocate memory for identifier\n");
        return 0;
    }
    print_token("IDENTIFIER", text);
    yylval.str = text;  // 将所有权转移给解析器
    // 不要在这里 free(text)! 解析器会负责释放
    return IDENTIFIER;
}
#line 293 "src/lexer.c"
yy12:
	++YYCURSOR;
#line 326 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("PERCENT", ""); return PERCENT; }
#line 298 "src/lexer.c"
yy13:
	yych = *++YYCURSOR;
	switch (yych) {
		case '&': goto yy63;
		default: goto yy3;
	}
yy14:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\'': goto yy64;
		case '\\': goto yy65;
		default: goto yy14;
	}
yy15:
	++YYCURSOR;
#line 368 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("LPAREN", ""); return LPAREN; }
#line 316 "src/lexer.c"
yy16:
	++YYCURSOR;
#line 369 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("RPAREN", ""); return RPAREN; }
#line 321 "src/lexer.c"
yy17:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy66;
		default: goto yy18;
	}
yy18:
#line 324 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("STAR", ""); return STAR; }
#line 331 "src/lexer.c"
yy19:
	yych = *++YYCURSOR;
	switch (yych) {
		case '+': goto yy67;
		case '=': goto yy68;
		default: goto yy20;
	}
yy20:
#line 322 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("PLUS", ""); return PLUS; }
#line 342 "src/lexer.c"
yy21:
	++YYCURSOR;
#line 373 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("COMMA", ""); return COMMA; }
#line 347 "src/lexer.c"
yy22:
	yych = *++YYCURSOR;
	switch (yych) {
		case '-': goto yy69;
		case '=': goto yy70;
		default: goto yy23;
	}
yy23:
#line 323 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("MINUS", ""); return MINUS; }
#line 358 "src/lexer.c"
yy24:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '.': goto yy71;
		default: goto yy25;
	}
yy25:
#line 363 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("DOT", ""); return DOT; }
#line 369 "src/lexer.c"
yy26:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\n': goto yy27;
		case '*': goto yy75;
		case '/': goto yy76;
		case '=': goto yy78;
		default: goto yy74;
	}
yy27:
#line 325 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("SLASH", ""); return SLASH; }
#line 383 "src/lexer.c"
yy28:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy28;
		default: goto yy29;
	}
yy29:
#line 260 "src/lexer.l"
	{
    global_scanner->pos += cursor - start;
    char *text = strndup((char*)start, cursor - start);
    if (!text) {
        fprintf(stderr, "LEXER: Failed to allocate memory for number\n");
        return 0;
    }
    print_token("NUMBER", text);
    yylval.str = text;  // 将所有权转移给解析器
    // 不要在这里 free(text)! 解析器会负责释放
    return NUMBER;
}
#line 413 "src/lexer.c"
yy30:
	++YYCURSOR;
#line 364 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("COLON", ""); return COLON; }
#line 418 "src/lexer.c"
yy31:
	++YYCURSOR;
#line 372 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("SEMICOLON", ""); return SEMICOLON; }
#line 423 "src/lexer.c"
yy32:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy81;
		default: goto yy33;
	}
yy33:
#line 330 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("LT", ""); return LT; }
#line 433 "src/lexer.c"
yy34:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy82;
		case '>': goto yy84;
		default: goto yy35;
	}
yy35:
#line 327 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("EQUALS", ""); return EQUALS; }
#line 444 "src/lexer.c"
yy36:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy85;
		default: goto yy37;
	}
yy37:
#line 332 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("GT", ""); return GT; }
#line 454 "src/lexer.c"
yy38:
	++YYCURSOR;
#line 365 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("QUESTION", ""); return QUESTION; }
#line 459 "src/lexer.c"
yy39:
	++YYCURSOR;
#line 361 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("LBRACKET", ""); return LBRACKET; }
#line 464 "src/lexer.c"
yy40:
	++YYCURSOR;
#line 362 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("RBRACKET", ""); return RBRACKET; }
#line 469 "src/lexer.c"
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\\': goto yy86;
		case '`': goto yy87;
		default: goto yy41;
	}
yy42:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy88;
		default: goto yy10;
	}
yy43:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy89;
		case 'l': goto yy90;
		case 'o': goto yy91;
		default: goto yy10;
	}
yy44:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy92;
		default: goto yy10;
	}
yy45:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy93;
		case 'x': goto yy94;
		default: goto yy10;
	}
yy46:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy95;
		case 'i': goto yy96;
		case 'o': goto yy97;
		case 'u': goto yy98;
		default: goto yy10;
	}
yy47:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'f': goto yy99;
		default: goto yy10;
	}
yy48:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy101;
		default: goto yy10;
	}
yy49:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy102;
		case 'u': goto yy103;
		default: goto yy10;
	}
yy50:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy104;
		default: goto yy10;
	}
yy51:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy105;
		case 'u': goto yy106;
		case 'w': goto yy107;
		default: goto yy10;
	}
yy52:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'h': goto yy108;
		case 'r': goto yy109;
		default: goto yy10;
	}
yy53:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy110;
		default: goto yy10;
	}
yy54:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy111;
		default: goto yy10;
	}
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'h': goto yy112;
		default: goto yy10;
	}
yy56:
	++YYCURSOR;
#line 370 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("LBRACE", ""); return LBRACE; }
#line 575 "src/lexer.c"
yy57:
	yych = *++YYCURSOR;
	switch (yych) {
		case '|': goto yy113;
		default: goto yy3;
	}
yy58:
	++YYCURSOR;
#line 371 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("RBRACE", ""); return RBRACE; }
#line 586 "src/lexer.c"
yy59:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy114;
		default: goto yy60;
	}
yy60:
#line 329 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("NOT_EQ", ""); return NOT_EQ; }
#line 596 "src/lexer.c"
yy61:
	++YYCURSOR;
#line 275 "src/lexer.l"
	{
    global_scanner->pos += cursor - start;
    char *text = strndup((char*)start, cursor - start);
    if (!text) {
        fprintf(stderr, "LEXER: Failed to allocate memory for string\n");
        return 0;
    }
    print_token("STRING", text);
    yylval.str = text;
    return STRING;
}
#line 611 "src/lexer.c"
yy62:
	++YYCURSOR;
	goto yy8;
yy63:
	++YYCURSOR;
#line 335 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("AND", ""); return AND; }
#line 619 "src/lexer.c"
yy64:
	++YYCURSOR;
#line 288 "src/lexer.l"
	{
    global_scanner->pos += cursor - start;
    char *text = strndup((char*)start, cursor - start);
    if (!text) {
        fprintf(stderr, "LEXER: Failed to allocate memory for string\n");
        return 0;
    }
    print_token("STRING", text);
    yylval.str = text;
    return STRING;
}
#line 634 "src/lexer.c"
yy65:
	++YYCURSOR;
	goto yy14;
yy66:
	++YYCURSOR;
#line 345 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("STAR_EQ", ""); return STAR_EQ; }
#line 642 "src/lexer.c"
yy67:
	++YYCURSOR;
#line 341 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("PLUS_PLUS", ""); return PLUS_PLUS; }
#line 647 "src/lexer.c"
yy68:
	++YYCURSOR;
#line 343 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("PLUS_EQ", ""); return PLUS_EQ; }
#line 652 "src/lexer.c"
yy69:
	++YYCURSOR;
#line 342 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("MINUS_MINUS", ""); return MINUS_MINUS; }
#line 657 "src/lexer.c"
yy70:
	++YYCURSOR;
#line 344 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("MINUS_EQ", ""); return MINUS_EQ; }
#line 662 "src/lexer.c"
yy71:
	yych = *++YYCURSOR;
	switch (yych) {
		case '.': goto yy115;
		default: goto yy72;
	}
yy72:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
		case 0: goto yy25;
		case 1: goto yy27;
		case 2: goto yy79;
		default: goto yy117;
	}
yy73:
	yych = *++YYCURSOR;
yy74:
	switch (yych) {
		case '\n': goto yy72;
		case '/': goto yy116;
		case '\\': goto yy80;
		default: goto yy73;
	}
yy75:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy118;
		case '*': goto yy119;
		case '/': goto yy120;
		case '\\': goto yy121;
		default: goto yy75;
	}
yy76:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n':
		case '\r': goto yy77;
		default: goto yy76;
	}
yy77:
#line 59 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    printf("LEXER: Skipped comment\n");
    goto scan; 
}
#line 709 "src/lexer.c"
yy78:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\n': goto yy79;
		default: goto yy74;
	}
yy79:
#line 346 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("SLASH_EQ", ""); return SLASH_EQ; }
#line 720 "src/lexer.c"
yy80:
	++YYCURSOR;
	goto yy73;
yy81:
	++YYCURSOR;
#line 331 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("LE", ""); return LE; }
#line 728 "src/lexer.c"
yy82:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy122;
		default: goto yy83;
	}
yy83:
#line 328 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("EQ_EQ", ""); return EQ_EQ; }
#line 738 "src/lexer.c"
yy84:
	++YYCURSOR;
#line 349 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start; 
    print_token("ARROW", ""); 
    return ARROW; 
}
#line 747 "src/lexer.c"
yy85:
	++YYCURSOR;
#line 333 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("GE", ""); return GE; }
#line 752 "src/lexer.c"
yy86:
	++YYCURSOR;
	goto yy41;
yy87:
	++YYCURSOR;
#line 245 "src/lexer.l"
	{
    global_scanner->pos += cursor - start;
    char *text = strndup((char*)start + 1, cursor - start - 2); // 去掉反引号
    if (!text) {
        fprintf(stderr, "LEXER: Failed to allocate memory for template string\n");
        return 0;
    }
    print_token("TEMPLATE_STRING", text);
    
    // 创建字符串节点（简化处理，将模板字符串当作普通字符串）
    yylval.str = text;  // 将所有权转移给解析器
    return TEMPLATE_STRING;
}
#line 772 "src/lexer.c"
yy88:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy123;
		default: goto yy10;
	}
yy89:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy124;
		case 't': goto yy125;
		default: goto yy10;
	}
yy90:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy126;
		default: goto yy10;
	}
yy91:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy127;
		default: goto yy10;
	}
yy92:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'f': goto yy128;
		default: goto yy10;
	}
yy93:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy129;
		default: goto yy10;
	}
yy94:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy130;
		default: goto yy10;
	}
yy95:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy131;
		default: goto yy10;
	}
yy96:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy132;
		default: goto yy10;
	}
yy97:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy133;
		default: goto yy10;
	}
yy98:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy135;
		default: goto yy10;
	}
yy99:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy100;
	}
yy100:
#line 71 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("IF", "");
    return IF; 
}
#line 916 "src/lexer.c"
yy101:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy136;
		default: goto yy10;
	}
yy102:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'w': goto yy138;
		default: goto yy10;
	}
yy103:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy140;
		default: goto yy10;
	}
yy104:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy141;
		default: goto yy10;
	}
yy105:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy142;
		default: goto yy10;
	}
yy106:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'p': goto yy143;
		default: goto yy10;
	}
yy107:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy144;
		default: goto yy10;
	}
yy108:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy145;
		default: goto yy10;
	}
yy109:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'u': goto yy146;
		case 'y': goto yy147;
		default: goto yy10;
	}
yy110:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy149;
		default: goto yy10;
	}
yy111:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy150;
		default: goto yy10;
	}
yy112:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy152;
		default: goto yy10;
	}
yy113:
	++YYCURSOR;
#line 336 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("OR", ""); return OR; }
#line 994 "src/lexer.c"
yy114:
	++YYCURSOR;
#line 340 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("STRICT_NOT_EQ", ""); return STRICT_NOT_EQ; }
#line 999 "src/lexer.c"
yy115:
	++YYCURSOR;
#line 354 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start; 
    print_token("DOT_DOT_DOT", ""); 
    return DOT_DOT_DOT; 
}
#line 1008 "src/lexer.c"
yy116:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'g':
		case 'i':
		case 'm':
		case 'y': goto yy116;
		default: goto yy117;
	}
yy117:
#line 214 "src/lexer.l"
	{
    global_scanner->pos += cursor - start;
    
    // 简单提取：从第一个/到最后一个/之间的内容
    const char* start_ptr = (const char*)start + 1;
    const char* end_ptr = (const char*)cursor - 1;
    
    // 找到最后一个斜杠
    while (end_ptr > start_ptr && *end_ptr != '/') {
        end_ptr--;
    }
    
    if (end_ptr > start_ptr) {
        char* pattern = strndup(start_ptr, end_ptr - start_ptr);
        char* flags = strndup(end_ptr + 1, (const char*)cursor - end_ptr - 1);
        
        print_token("REGEXP_LITERAL", pattern);
        
        // 创建正则表达式字面量节点
        yylval.node = create_regexp_literal(pattern, flags);
        free(pattern);
        free(flags);
        
        return REGEXP_LITERAL;
    } else {
        fprintf(stderr, "LEXER: Invalid regexp literal\n");
        return 0;
    }
}
#line 1049 "src/lexer.c"
yy118:
	yych = *++YYCURSOR;
	switch (yych) {
		case '*': goto yy153;
		default: goto yy118;
	}
yy119:
	yych = *++YYCURSOR;
	switch (yych) {
		case '*': goto yy158;
		default: goto yy155;
	}
yy120:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '*': goto yy153;
		case 'g':
		case 'i':
		case 'm':
		case 'y': goto yy120;
		default: goto yy118;
	}
yy121:
	yych = *++YYCURSOR;
	switch (yych) {
		case '*': goto yy119;
		default: goto yy75;
	}
yy122:
	++YYCURSOR;
#line 339 "src/lexer.l"
	{ global_scanner->pos += cursor - start; print_token("STRICT_EQ", ""); return STRICT_EQ; }
#line 1083 "src/lexer.c"
yy123:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy160;
		default: goto yy10;
	}
yy124:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy161;
		default: goto yy10;
	}
yy125:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'c': goto yy163;
		default: goto yy10;
	}
yy126:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy164;
		default: goto yy10;
	}
yy127:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy165;
		case 't': goto yy166;
		default: goto yy10;
	}
yy128:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy167;
		default: goto yy10;
	}
yy129:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy168;
		default: goto yy10;
	}
yy130:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy170;
		default: goto yy10;
	}
yy131:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy171;
		default: goto yy10;
	}
yy132:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy172;
		default: goto yy10;
	}
yy133:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy134;
	}
yy134:
#line 86 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("FOR", "");
    return FOR; 
}
#line 1221 "src/lexer.c"
yy135:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'c': goto yy173;
		default: goto yy10;
	}
yy136:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy137;
	}
yy137:
#line 101 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("LET", "");
    return LET; 
}
#line 1304 "src/lexer.c"
yy138:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy139;
	}
yy139:
#line 151 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("NEW", "");
    return NEW; 
}
#line 1381 "src/lexer.c"
yy140:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy174;
		default: goto yy10;
	}
yy141:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'u': goto yy176;
		default: goto yy10;
	}
yy142:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy177;
		default: goto yy10;
	}
yy143:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy178;
		default: goto yy10;
	}
yy144:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy179;
		default: goto yy10;
	}
yy145:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy180;
		default: goto yy10;
	}
yy146:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy182;
		default: goto yy10;
	}
yy147:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy148;
	}
yy148:
#line 197 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("TRY", "");
    return TRY; 
}
#line 1500 "src/lexer.c"
yy149:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy184;
		default: goto yy10;
	}
yy150:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy151;
	}
yy151:
#line 96 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("VAR", "");
    return VAR; 
}
#line 1583 "src/lexer.c"
yy152:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy185;
		default: goto yy10;
	}
yy153:
	yych = *++YYCURSOR;
	switch (yych) {
		case '*': goto yy186;
		default: goto yy157;
	}
yy154:
	yych = *++YYCURSOR;
yy155:
	switch (yych) {
		case '\n': goto yy156;
		case '*': goto yy187;
		case '/': goto yy116;
		case '\\': goto yy159;
		default: goto yy154;
	}
yy156:
	yych = *++YYCURSOR;
yy157:
	switch (yych) {
		case '*': goto yy188;
		case '/': goto yy72;
		default: goto yy156;
	}
yy158:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy156;
		case '*': goto yy158;
		case '/': goto yy189;
		case '\\': goto yy159;
		default: goto yy154;
	}
yy159:
	yych = *++YYCURSOR;
	switch (yych) {
		case '*': goto yy187;
		case '/': goto yy73;
		default: goto yy154;
	}
yy160:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'k': goto yy191;
		default: goto yy10;
	}
yy161:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy162;
	}
yy162:
#line 187 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("CASE", "");
    return CASE; 
}
#line 1712 "src/lexer.c"
yy163:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'h': goto yy193;
		default: goto yy10;
	}
yy164:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy195;
		default: goto yy10;
	}
yy165:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy197;
		default: goto yy10;
	}
yy166:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy199;
		default: goto yy10;
	}
yy167:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'u': goto yy200;
		default: goto yy10;
	}
yy168:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy169;
	}
yy169:
#line 76 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("ELSE", "");
    return ELSE; 
}
#line 1819 "src/lexer.c"
yy170:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy201;
		default: goto yy10;
	}
yy171:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy202;
		default: goto yy10;
	}
yy172:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy204;
		default: goto yy10;
	}
yy173:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy205;
		default: goto yy10;
	}
yy174:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy175;
	}
yy175:
#line 136 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("NULL_LITERAL", "");
    return NULL_LITERAL; 
}
#line 1920 "src/lexer.c"
yy176:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy206;
		default: goto yy10;
	}
yy177:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy207;
		default: goto yy10;
	}
yy178:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy208;
		default: goto yy10;
	}
yy179:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'c': goto yy210;
		default: goto yy10;
	}
yy180:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy181;
	}
yy181:
#line 156 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("THIS", "");
    return THIS; 
}
#line 2021 "src/lexer.c"
yy182:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy183;
	}
yy183:
#line 126 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("TRUE", "");
    return TRUE; 
}
#line 2098 "src/lexer.c"
yy184:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'f': goto yy211;
		default: goto yy10;
	}
yy185:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy212;
		default: goto yy10;
	}
yy186:
	yych = *++YYCURSOR;
	switch (yych) {
		case '*': goto yy186;
		case '/': goto yy214;
		default: goto yy156;
	}
yy187:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy72;
		case '*': goto yy187;
		case '/': goto yy189;
		case '\\': goto yy80;
		default: goto yy73;
	}
yy188:
	yych = *++YYCURSOR;
	switch (yych) {
		case '*': goto yy188;
		case '/': goto yy214;
		default: goto yy72;
	}
yy189:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'g':
		case 'i':
		case 'm':
		case 'y': goto yy116;
		default: goto yy190;
	}
yy190:
#line 64 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    printf("LEXER: Skipped block comment\n");
    goto scan; 
}
#line 2150 "src/lexer.c"
yy191:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy192;
	}
yy192:
#line 116 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("BREAK", "");
    return BREAK; 
}
#line 2227 "src/lexer.c"
yy193:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy194;
	}
yy194:
#line 202 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("CATCH", "");
    return CATCH; 
}
#line 2304 "src/lexer.c"
yy195:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy196;
	}
yy196:
#line 146 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("CLASS", "");
    return CLASS; 
}
#line 2381 "src/lexer.c"
yy197:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		case 'r': goto yy215;
		default: goto yy198;
	}
yy198:
#line 106 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("CONST", "");
    return CONST; 
}
#line 2458 "src/lexer.c"
yy199:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy216;
		default: goto yy10;
	}
yy200:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy217;
		default: goto yy10;
	}
yy201:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy218;
		default: goto yy10;
	}
yy202:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy203;
	}
yy203:
#line 131 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("FALSE", "");
    return FALSE; 
}
#line 2553 "src/lexer.c"
yy204:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy219;
		default: goto yy10;
	}
yy205:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy220;
		default: goto yy10;
	}
yy206:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy221;
		default: goto yy10;
	}
yy207:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'c': goto yy223;
		default: goto yy10;
	}
yy208:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy209;
	}
yy209:
#line 161 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("SUPER", "");
    return SUPER; 
}
#line 2654 "src/lexer.c"
yy210:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'h': goto yy225;
		default: goto yy10;
	}
yy211:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy227;
		default: goto yy10;
	}
yy212:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy213;
	}
yy213:
#line 81 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("WHILE", "");
    return WHILE; 
}
#line 2743 "src/lexer.c"
yy214:
	++YYCURSOR;
	goto yy190;
yy215:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'u': goto yy228;
		default: goto yy10;
	}
yy216:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'u': goto yy229;
		default: goto yy10;
	}
yy217:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy230;
		default: goto yy10;
	}
yy218:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy232;
		default: goto yy10;
	}
yy219:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'y': goto yy234;
		default: goto yy10;
	}
yy220:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy236;
		default: goto yy10;
	}
yy221:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy222;
	}
yy222:
#line 111 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("RETURN", "");
    return RETURN; 
}
#line 2859 "src/lexer.c"
yy223:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy224;
	}
yy224:
#line 166 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("STATIC", "");
    return STATIC; 
}
#line 2936 "src/lexer.c"
yy225:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy226;
	}
yy226:
#line 182 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("SWITCH", "");
    return SWITCH; 
}
#line 3013 "src/lexer.c"
yy227:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy237;
		default: goto yy10;
	}
yy228:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'c': goto yy238;
		default: goto yy10;
	}
yy229:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy239;
		default: goto yy10;
	}
yy230:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy231;
	}
yy231:
#line 192 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("DEFAULT", "");
    return DEFAULT; 
}
#line 3108 "src/lexer.c"
yy232:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy233;
	}
yy233:
#line 171 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("EXTENDS", "");
    return EXTENDS; 
}
#line 3185 "src/lexer.c"
yy234:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy235;
	}
yy235:
#line 207 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("FINALLY", "");
    return FINALLY; 
}
#line 3262 "src/lexer.c"
yy236:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy241;
		default: goto yy10;
	}
yy237:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy243;
		default: goto yy10;
	}
yy238:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy244;
		default: goto yy10;
	}
yy239:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy240;
	}
yy240:
#line 121 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("CONTINUE", "");
    return CONTINUE; 
}
#line 3357 "src/lexer.c"
yy241:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy242;
	}
yy242:
#line 91 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("FUNCTION", "");
    return FUNCTION; 
}
#line 3434 "src/lexer.c"
yy243:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy245;
		default: goto yy10;
	}
yy244:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy247;
		default: goto yy10;
	}
yy245:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy246;
	}
yy246:
#line 141 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("UNDEFINED", "");
    return UNDEFINED; 
}
#line 3523 "src/lexer.c"
yy247:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy248;
		default: goto yy10;
	}
yy248:
	yych = *++YYCURSOR;
	switch (yych) {
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		default: goto yy249;
	}
yy249:
#line 176 "src/lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("CONSTRUCTOR", "");
    return CONSTRUCTOR; 
}
#line 3606 "src/lexer.c"
}
#line 387 "src/lexer.l"

}