/* Generated by re2c 3.1 on Thu Nov 13 17:32:26 2025 */
#line 1 "lexer.l"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "common.h"
#include "ast.h"           // 添加 ast.h
#include "parser_types.h"  // 添加 parser_types.h

// 包含 bison 生成的头文件
#include "parser.h"

#define YYCTYPE unsigned char
#define YYCURSOR cursor
#define YYLIMIT limit
#define YYMARKER marker
#define YYFILL(n) {}

// 全局变量用于跟踪输入
ScannerState *global_scanner = NULL;

void set_scanner(ScannerState *scanner) {
    global_scanner = scanner;
}

// 调试函数：打印token信息
void print_token(const char* name, const char* value) {
    printf("LEXER: Token %s", name);
    if (value && strlen(value) > 0) {
        printf(" ('%s')", value);
    }
    printf(" at position %d\n", global_scanner->pos);
}

int yylex(void) {
    const unsigned char *cursor, *marker;
    const unsigned char *start;
    
    if (!global_scanner || !global_scanner->input) {
        printf("LEXER: No input\n");
        return 0;
    }
    
    cursor = (const unsigned char *)global_scanner->input + global_scanner->pos;
    
scan:
    start = cursor;
    

#line 51 "lexer.c"
{
	unsigned char yych;
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy1;
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case ' ': goto yy4;
		case '!': goto yy6;
		case '"': goto yy8;
		case '%': goto yy9;
		case '&': goto yy10;
		case '\'': goto yy11;
		case '(': goto yy12;
		case ')': goto yy13;
		case '*': goto yy14;
		case '+': goto yy16;
		case ',': goto yy18;
		case '-': goto yy19;
		case '.': goto yy21;
		case '/': goto yy22;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy24;
		case ':': goto yy26;
		case ';': goto yy27;
		case '<': goto yy28;
		case '=': goto yy30;
		case '>': goto yy32;
		case '?': goto yy34;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'd':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'm':
		case 'o':
		case 'p':
		case 'q':
		case 's':
		case 'x':
		case 'y':
		case 'z': goto yy35;
		case '[': goto yy38;
		case ']': goto yy39;
		case 'b': goto yy40;
		case 'c': goto yy41;
		case 'e': goto yy42;
		case 'f': goto yy43;
		case 'i': goto yy44;
		case 'l': goto yy45;
		case 'n': goto yy46;
		case 'r': goto yy47;
		case 't': goto yy48;
		case 'u': goto yy49;
		case 'v': goto yy50;
		case 'w': goto yy51;
		case '{': goto yy52;
		case '|': goto yy53;
		case '}': goto yy54;
		default: goto yy2;
	}
yy1:
	++YYCURSOR;
#line 239 "lexer.l"
	{ 
    printf("LEXER: End of file\n");
    return 0; 
}
#line 159 "lexer.c"
yy2:
	++YYCURSOR;
yy3:
#line 245 "lexer.l"
	{ 
    fprintf(stderr, "LEXER: Invalid character: %c (0x%02x) at position %d\n", *start, *start, global_scanner->pos);
    global_scanner->pos += cursor - start;
    return 0;  // 返回0表示结束
}
#line 169 "lexer.c"
yy4:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case ' ': goto yy4;
		default: goto yy5;
	}
yy5:
#line 52 "lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    printf("LEXER: Skipped whitespace/newline\n");
    goto scan; 
}
#line 188 "lexer.c"
yy6:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy55;
		default: goto yy7;
	}
yy7:
#line 209 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("BANG", ""); return BANG; }
#line 198 "lexer.c"
yy8:
	yych = *++YYCURSOR;
	switch (yych) {
		case '"': goto yy57;
		case '\\': goto yy58;
		default: goto yy8;
	}
yy9:
	++YYCURSOR;
#line 201 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("PERCENT", ""); return PERCENT; }
#line 210 "lexer.c"
yy10:
	yych = *++YYCURSOR;
	switch (yych) {
		case '&': goto yy59;
		default: goto yy3;
	}
yy11:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\'': goto yy60;
		case '\\': goto yy61;
		default: goto yy11;
	}
yy12:
	++YYCURSOR;
#line 231 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("LPAREN", ""); return LPAREN; }
#line 228 "lexer.c"
yy13:
	++YYCURSOR;
#line 232 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("RPAREN", ""); return RPAREN; }
#line 233 "lexer.c"
yy14:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy62;
		default: goto yy15;
	}
yy15:
#line 199 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("STAR", ""); return STAR; }
#line 243 "lexer.c"
yy16:
	yych = *++YYCURSOR;
	switch (yych) {
		case '+': goto yy63;
		case '=': goto yy64;
		default: goto yy17;
	}
yy17:
#line 197 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("PLUS", ""); return PLUS; }
#line 254 "lexer.c"
yy18:
	++YYCURSOR;
#line 236 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("COMMA", ""); return COMMA; }
#line 259 "lexer.c"
yy19:
	yych = *++YYCURSOR;
	switch (yych) {
		case '-': goto yy65;
		case '=': goto yy66;
		default: goto yy20;
	}
yy20:
#line 198 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("MINUS", ""); return MINUS; }
#line 270 "lexer.c"
yy21:
	++YYCURSOR;
#line 226 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("DOT", ""); return DOT; }
#line 275 "lexer.c"
yy22:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '*': goto yy67;
		case '/': goto yy68;
		case '=': goto yy70;
		default: goto yy23;
	}
yy23:
#line 200 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("SLASH", ""); return SLASH; }
#line 287 "lexer.c"
yy24:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy24;
		default: goto yy25;
	}
yy25:
#line 148 "lexer.l"
	{
    global_scanner->pos += cursor - start;
    char *text = strndup((char*)start, cursor - start);
    if (!text) {
        fprintf(stderr, "LEXER: Failed to allocate memory for number\n");
        return 0;
    }
    print_token("NUMBER", text);
    yylval.str = text;  // 将所有权转移给解析器
    // 不要在这里 free(text)! 解析器会负责释放
    return NUMBER;
}
#line 317 "lexer.c"
yy26:
	++YYCURSOR;
#line 227 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("COLON", ""); return COLON; }
#line 322 "lexer.c"
yy27:
	++YYCURSOR;
#line 235 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("SEMICOLON", ""); return SEMICOLON; }
#line 327 "lexer.c"
yy28:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy71;
		default: goto yy29;
	}
yy29:
#line 205 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("LT", ""); return LT; }
#line 337 "lexer.c"
yy30:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy72;
		default: goto yy31;
	}
yy31:
#line 202 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("EQUALS", ""); return EQUALS; }
#line 347 "lexer.c"
yy32:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy74;
		default: goto yy33;
	}
yy33:
#line 207 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("GT", ""); return GT; }
#line 357 "lexer.c"
yy34:
	++YYCURSOR;
#line 228 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("QUESTION", ""); return QUESTION; }
#line 362 "lexer.c"
yy35:
	yych = *++YYCURSOR;
yy36:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy35;
		default: goto yy37;
	}
yy37:
#line 176 "lexer.l"
	{
    global_scanner->pos += cursor - start;
    char *text = strndup((char*)start, cursor - start);
    if (!text) {
        fprintf(stderr, "LEXER: Failed to allocate memory for identifier\n");
        return 0;
    }
    print_token("IDENTIFIER", text);
    yylval.str = text;  // 将所有权转移给解析器
    // 不要在这里 free(text)! 解析器会负责释放
    return IDENTIFIER;
}
#line 446 "lexer.c"
yy38:
	++YYCURSOR;
#line 224 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("LBRACKET", ""); return LBRACKET; }
#line 451 "lexer.c"
yy39:
	++YYCURSOR;
#line 225 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("RBRACKET", ""); return RBRACKET; }
#line 456 "lexer.c"
yy40:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy75;
		default: goto yy36;
	}
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy76;
		default: goto yy36;
	}
yy42:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy77;
		default: goto yy36;
	}
yy43:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy78;
		case 'o': goto yy79;
		case 'u': goto yy80;
		default: goto yy36;
	}
yy44:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'f': goto yy81;
		default: goto yy36;
	}
yy45:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy83;
		default: goto yy36;
	}
yy46:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'u': goto yy84;
		default: goto yy36;
	}
yy47:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy85;
		default: goto yy36;
	}
yy48:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy86;
		default: goto yy36;
	}
yy49:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy87;
		default: goto yy36;
	}
yy50:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy88;
		default: goto yy36;
	}
yy51:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'h': goto yy89;
		default: goto yy36;
	}
yy52:
	++YYCURSOR;
#line 233 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("LBRACE", ""); return LBRACE; }
#line 535 "lexer.c"
yy53:
	yych = *++YYCURSOR;
	switch (yych) {
		case '|': goto yy90;
		default: goto yy3;
	}
yy54:
	++YYCURSOR;
#line 234 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("RBRACE", ""); return RBRACE; }
#line 546 "lexer.c"
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy91;
		default: goto yy56;
	}
yy56:
#line 204 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("NOT_EQ", ""); return NOT_EQ; }
#line 556 "lexer.c"
yy57:
	++YYCURSOR;
#line 162 "lexer.l"
	{
    global_scanner->pos += cursor - start;
    char *text = strndup((char*)start, cursor - start);
    if (!text) {
        fprintf(stderr, "LEXER: Failed to allocate memory for string\n");
        return 0;
    }
    print_token("STRING", text);
    yylval.str = text;  // 将所有权转移给解析器
    // 不要在这里 free(text)! 解析器会负责释放
    return STRING;
}
#line 572 "lexer.c"
yy58:
	++YYCURSOR;
	goto yy8;
yy59:
	++YYCURSOR;
#line 210 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("AND", ""); return AND; }
#line 580 "lexer.c"
yy60:
	++YYCURSOR;
#line 188 "lexer.l"
	{
    global_scanner->pos += cursor - start;
    char *text = strndup((char*)start, cursor - start);
    print_token("STRING", text);
    free(text);
    return STRING;
}
#line 591 "lexer.c"
yy61:
	++YYCURSOR;
	goto yy11;
yy62:
	++YYCURSOR;
#line 220 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("STAR_EQ", ""); return STAR_EQ; }
#line 599 "lexer.c"
yy63:
	++YYCURSOR;
#line 216 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("PLUS_PLUS", ""); return PLUS_PLUS; }
#line 604 "lexer.c"
yy64:
	++YYCURSOR;
#line 218 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("PLUS_EQ", ""); return PLUS_EQ; }
#line 609 "lexer.c"
yy65:
	++YYCURSOR;
#line 217 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("MINUS_MINUS", ""); return MINUS_MINUS; }
#line 614 "lexer.c"
yy66:
	++YYCURSOR;
#line 219 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("MINUS_EQ", ""); return MINUS_EQ; }
#line 619 "lexer.c"
yy67:
	yych = *++YYCURSOR;
	switch (yych) {
		case '*': goto yy92;
		default: goto yy67;
	}
yy68:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n':
		case '\r': goto yy69;
		default: goto yy68;
	}
yy69:
#line 59 "lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    printf("LEXER: Skipped comment\n");
    goto scan; 
}
#line 640 "lexer.c"
yy70:
	++YYCURSOR;
#line 221 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("SLASH_EQ", ""); return SLASH_EQ; }
#line 645 "lexer.c"
yy71:
	++YYCURSOR;
#line 206 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("LE", ""); return LE; }
#line 650 "lexer.c"
yy72:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy94;
		default: goto yy73;
	}
yy73:
#line 203 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("EQ_EQ", ""); return EQ_EQ; }
#line 660 "lexer.c"
yy74:
	++YYCURSOR;
#line 208 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("GE", ""); return GE; }
#line 665 "lexer.c"
yy75:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy95;
		default: goto yy36;
	}
yy76:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy96;
		default: goto yy36;
	}
yy77:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy97;
		default: goto yy36;
	}
yy78:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy98;
		default: goto yy36;
	}
yy79:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy99;
		default: goto yy36;
	}
yy80:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy101;
		default: goto yy36;
	}
yy81:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy35;
		default: goto yy82;
	}
yy82:
#line 71 "lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("IF", "");
    return IF; 
}
#line 777 "lexer.c"
yy83:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy102;
		default: goto yy36;
	}
yy84:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy104;
		default: goto yy36;
	}
yy85:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy105;
		default: goto yy36;
	}
yy86:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'u': goto yy106;
		default: goto yy36;
	}
yy87:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy107;
		default: goto yy36;
	}
yy88:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy108;
		default: goto yy36;
	}
yy89:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy110;
		default: goto yy36;
	}
yy90:
	++YYCURSOR;
#line 211 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("OR", ""); return OR; }
#line 824 "lexer.c"
yy91:
	++YYCURSOR;
#line 215 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("STRICT_NOT_EQ", ""); return STRICT_NOT_EQ; }
#line 829 "lexer.c"
yy92:
	yych = *++YYCURSOR;
	switch (yych) {
		case '*': goto yy113;
		default: goto yy112;
	}
yy93:
	YYCURSOR = YYMARKER;
	goto yy23;
yy94:
	++YYCURSOR;
#line 214 "lexer.l"
	{ global_scanner->pos += cursor - start; print_token("STRICT_EQ", ""); return STRICT_EQ; }
#line 843 "lexer.c"
yy95:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy114;
		default: goto yy36;
	}
yy96:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy115;
		case 't': goto yy116;
		default: goto yy36;
	}
yy97:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy117;
		default: goto yy36;
	}
yy98:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy119;
		default: goto yy36;
	}
yy99:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy35;
		default: goto yy100;
	}
yy100:
#line 86 "lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("FOR", "");
    return FOR; 
}
#line 944 "lexer.c"
yy101:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'c': goto yy120;
		default: goto yy36;
	}
yy102:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy35;
		default: goto yy103;
	}
yy103:
#line 101 "lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("LET", "");
    return LET; 
}
#line 1026 "lexer.c"
yy104:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy121;
		default: goto yy36;
	}
yy105:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'u': goto yy123;
		default: goto yy36;
	}
yy106:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy124;
		default: goto yy36;
	}
yy107:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy126;
		default: goto yy36;
	}
yy108:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy35;
		default: goto yy109;
	}
yy109:
#line 96 "lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("VAR", "");
    return VAR; 
}
#line 1126 "lexer.c"
yy110:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy127;
		default: goto yy36;
	}
yy111:
	yych = *++YYCURSOR;
yy112:
	switch (yych) {
		case '*': goto yy128;
		case '/': goto yy93;
		default: goto yy111;
	}
yy113:
	yych = *++YYCURSOR;
	switch (yych) {
		case '*': goto yy113;
		case '/': goto yy129;
		default: goto yy111;
	}
yy114:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'k': goto yy130;
		default: goto yy36;
	}
yy115:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy132;
		default: goto yy36;
	}
yy116:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy134;
		default: goto yy36;
	}
yy117:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy35;
		default: goto yy118;
	}
yy118:
#line 76 "lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("ELSE", "");
    return ELSE; 
}
#line 1241 "lexer.c"
yy119:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy135;
		default: goto yy36;
	}
yy120:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy137;
		default: goto yy36;
	}
yy121:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy35;
		default: goto yy122;
	}
yy122:
#line 136 "lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("NULL_LITERAL", "");
    return NULL_LITERAL; 
}
#line 1329 "lexer.c"
yy123:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy138;
		default: goto yy36;
	}
yy124:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy35;
		default: goto yy125;
	}
yy125:
#line 126 "lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("TRUE", "");
    return TRUE; 
}
#line 1411 "lexer.c"
yy126:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'f': goto yy139;
		default: goto yy36;
	}
yy127:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy140;
		default: goto yy36;
	}
yy128:
	yych = *++YYCURSOR;
	switch (yych) {
		case '*': goto yy128;
		case '/': goto yy129;
		default: goto yy93;
	}
yy129:
	++YYCURSOR;
#line 64 "lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    printf("LEXER: Skipped block comment\n");
    goto scan; 
}
#line 1439 "lexer.c"
yy130:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy35;
		default: goto yy131;
	}
yy131:
#line 116 "lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("BREAK", "");
    return BREAK; 
}
#line 1515 "lexer.c"
yy132:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy35;
		default: goto yy133;
	}
yy133:
#line 106 "lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("CONST", "");
    return CONST; 
}
#line 1591 "lexer.c"
yy134:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy142;
		default: goto yy36;
	}
yy135:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy35;
		default: goto yy136;
	}
yy136:
#line 131 "lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("FALSE", "");
    return FALSE; 
}
#line 1673 "lexer.c"
yy137:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy143;
		default: goto yy36;
	}
yy138:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy144;
		default: goto yy36;
	}
yy139:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy146;
		default: goto yy36;
	}
yy140:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy35;
		default: goto yy141;
	}
yy141:
#line 81 "lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("WHILE", "");
    return WHILE; 
}
#line 1767 "lexer.c"
yy142:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'u': goto yy147;
		default: goto yy36;
	}
yy143:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy148;
		default: goto yy36;
	}
yy144:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy35;
		default: goto yy145;
	}
yy145:
#line 111 "lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("RETURN", "");
    return RETURN; 
}
#line 1855 "lexer.c"
yy146:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy149;
		default: goto yy36;
	}
yy147:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy150;
		default: goto yy36;
	}
yy148:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy152;
		default: goto yy36;
	}
yy149:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy154;
		default: goto yy36;
	}
yy150:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy35;
		default: goto yy151;
	}
yy151:
#line 121 "lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("CONTINUE", "");
    return CONTINUE; 
}
#line 1955 "lexer.c"
yy152:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy35;
		default: goto yy153;
	}
yy153:
#line 91 "lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("FUNCTION", "");
    return FUNCTION; 
}
#line 2031 "lexer.c"
yy154:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy155;
		default: goto yy36;
	}
yy155:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy35;
		default: goto yy156;
	}
yy156:
#line 141 "lexer.l"
	{ 
    global_scanner->pos += cursor - start;
    print_token("UNDEFINED", "");
    return UNDEFINED; 
}
#line 2113 "lexer.c"
}
#line 250 "lexer.l"

}